port: 3000

db:
  type: postgres
  host: postgres-production-50cf.up.railway.app
  port: 5432
  user: postgres
  pass: xFqeVduUNgCPbSBqfwWHcJBCkNeqnnm
  db: railway
  ssl: false

bindIP: 0.0.0.0

logLevel: info
